name: Auto Commit Every 4 Hours

on:
  schedule:
    - cron: "0 */4 * * *"
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Update daily log
      run: |
        echo "Update: $(date -u)" >> daily_log.txt

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"

        git add daily_log.txt
        git commit -m "Auto-commit: $(date -u)" || echo "No changes to commit"
        git push origin main
